feat(services): add Twitch service
Skillz4Killz/gamer-deno pull request #51
Opened 2021-01-22 22:03 UTC by itohatweb

Closes: https://github.com/Skillz4Killz/gamer-deno/issues/33

2021-01-26 16:28 UTC, Skillz4Killz requested changes

2021-01-26 16:28 UTC, Skillz4Killz commented on services/twitch/mod.ts
> +  const twitchSubs = await db.twitch.findMany({}, true);
```suggestion
  const twitchSubs = await db.twitch.getAll(true);
```

2021-01-26 17:15 UTC, itohatweb commented on services/twitch/mod.ts
> +  if (!bearer.accessToken || bearer.expiresAt < Date.now() + 300000) {
The token is valid for idk how long anymore. So basically this is here so we don't fetch a new token on every request but only when it's needed. Basically: if token live time < 5 min get new token

2021-01-28 01:20 UTC, Skillz4Killz approved these changes

2021-01-28 15:33 UTC, merged